INSERT INTO Country (iso,created,countryname) VALUES

('AFG',GETDATE(),'Afghanistan'),
('ALB',GETDATE(),'Albanien'),
('ATA',GETDATE(),'Antarktis'),
('DZA',GETDATE(),'Algerien'),
('ASM',GETDATE(),'Amerikanisch-Samoa'),
('AND',GETDATE(),'Andorra'),
('AGO',GETDATE(),'Angola'),
('ATG',GETDATE(),'Antigua und Barbuda'),
('AZE',GETDATE(),'Aserbaidschan'),
('ARG',GETDATE(),'Argentinien'),
('AUS',GETDATE(),'Australien'),
('AUT',GETDATE(),'Österreich'),
('BHS',GETDATE(),'Bahamas'),
('BHR',GETDATE(),'Bahrain'),
('BGD',GETDATE(),'Bangladesch'),
('ARM',GETDATE(),'Armenien'),
('BRB',GETDATE(),'Barbados'),
('BEL',GETDATE(),'Belgien'),
('BMU',GETDATE(),'Bermuda'),
('BTN',GETDATE(),'Bhutan'),
('BOL',GETDATE(),'Bolivien'),
('BIH',GETDATE(),'Bosnien und Herzegowina'),
('BWA',GETDATE(),'Botswana'),
('BVT',GETDATE(),'Bouvetinsel'),
('BRA',GETDATE(),'Brasilien'),
('BLZ',GETDATE(),'Belize'),
('IOT',GETDATE(),'Britisches Territorium im Indischen Ozean'),
('SLB',GETDATE(),'Salomonen'),
('VGB',GETDATE(),'Britische Jungferninseln'),
('BRN',GETDATE(),'Brunei Darussalam'),
('BGR',GETDATE(),'Bulgarien'),
('MMR',GETDATE(),'Myanmar'),
('BDI',GETDATE(),'Burundi'),
('BLR',GETDATE(),'Belarus'),
('KHM',GETDATE(),'Kambodscha'),
('CMR',GETDATE(),'Kamerun'),
('CAN',GETDATE(),'Kanada'),
('CPV',GETDATE(),'Kap Verde'),
('CYM',GETDATE(),'Kaimaninseln'),
('CAF',GETDATE(),'Zentralafrikanische Republik'),
('LKA',GETDATE(),'Sri Lanka'),
('TCD',GETDATE(),'Tschad'),
('CHL',GETDATE(),'Chile'),
('CHN',GETDATE(),'China'),
('TWN',GETDATE(),'Taiwan'),
('CXR',GETDATE(),'Weihnachtsinsel'),
('CCK',GETDATE(),'Kokosinseln'),
('COL',GETDATE(),'Kolumbien'),
('COM',GETDATE(),'Komoren'),
('MYT',GETDATE(),'Mayotte'),
('COG',GETDATE(),'Republik Kongo'),
('COD',GETDATE(),'Demokratische Republik Kongo'),
('COK',GETDATE(),'Cookinseln'),
('CRI',GETDATE(),'Costa Rica'),
('HRV',GETDATE(),'Kroatien'),
('CUB',GETDATE(),'Kuba'),
('CYP',GETDATE(),'Zypern'),
('CZE',GETDATE(),'Tschechische Republik'),
('BEN',GETDATE(),'Benin'),
('DNK',GETDATE(),'Dänemark'),
('DMA',GETDATE(),'Dominica'),
('DOM',GETDATE(),'Dominikanische Republik'),
('ECU',GETDATE(),'Ecuador'),
('SLV',GETDATE(),'El Salvador'),
('GNQ',GETDATE(),'Äquatorialguinea'),
('ETH',GETDATE(),'Äthiopien'),
('ERI',GETDATE(),'Eritrea'),
('EST',GETDATE(),'Estland'),
('FRO',GETDATE(),'Färöer'),
('FLK',GETDATE(),'Falklandinseln'),
('SGS',GETDATE(),'Südgeorgien und die Südlichen Sandwichinseln'),
('FJI',GETDATE(),'Fidschi'),
('FIN',GETDATE(),'Finnland'),
('ALA',GETDATE(),'Åland-Inseln'),
('FRA',GETDATE(),'Frankreich'),
('GUF',GETDATE(),'Französisch-Guayana'),
('PYF',GETDATE(),'Französisch-Polynesien'),
('ATF',GETDATE(),'Französische Süd- und Antarktisgebiete'),
('DJI',GETDATE(),'Dschibuti'),
('GAB',GETDATE(),'Gabun'),
('GEO',GETDATE(),'Georgien'),
('GMB',GETDATE(),'Gambia'),
('PSE',GETDATE(),'Palästinensische Autonomiegebiete'),
('DEU',GETDATE(),'Deutschland'),
('GHA',GETDATE(),'Ghana'),
('GIB',GETDATE(),'Gibraltar'),
('KIR',GETDATE(),'Kiribati'),
('GRC',GETDATE(),'Griechenland'),
('GRL',GETDATE(),'Grönland'),
('GRD',GETDATE(),'Grenada'),
('GLP',GETDATE(),'Guadeloupe'),
('GUM',GETDATE(),'Guam'),
('GTM',GETDATE(),'Guatemala'),
('GIN',GETDATE(),'Guinea'),
('GUY',GETDATE(),'Guyana'),
('HTI',GETDATE(),'Haiti'),
('HMD',GETDATE(),'Heard und McDonaldinseln'),
('VAT',GETDATE(),'Vatikanstadt'),
('HND',GETDATE(),'Honduras'),
('HKG',GETDATE(),'Hongkong'),
('HUN',GETDATE(),'Ungarn'),
('ISL',GETDATE(),'Island'),
('IND',GETDATE(),'Indien'),
('IDN',GETDATE(),'Indonesien'),
('IRN',GETDATE(),'Islamische Republik Iran'),
('IRQ',GETDATE(),'Irak'),
('IRL',GETDATE(),'Irland'),
('ISR',GETDATE(),'Israel'),
('ITA',GETDATE(),'Italien'),
('CIV',GETDATE(),'slonoviny'),
('JAM',GETDATE(),'Jamaika'),
('JPN',GETDATE(),'Japan'),
('KAZ',GETDATE(),'Kasachstan'),
('JOR',GETDATE(),'Jordanien'),
('KEN',GETDATE(),'Kenia'),
('PRK',GETDATE(),'Demokratische Volksrepublik Korea'),
('KOR',GETDATE(),'Republik Korea'),
('KWT',GETDATE(),'Kuwait'),
('KGZ',GETDATE(),'Kirgisistan'),
('LAO',GETDATE(),'Demokratische Volksrepublik Laos'),
('LBN',GETDATE(),'Libanon'),
('LSO',GETDATE(),'Lesotho'),
('LVA',GETDATE(),'Lettland'),
('LBR',GETDATE(),'Liberia'),
('LBY',GETDATE(),'Libysch-Arabische Dschamahirija'),
('LIE',GETDATE(),'Liechtenstein'),
('LTU',GETDATE(),'Litauen'),
('LUX',GETDATE(),'Luxemburg'),
('MAC',GETDATE(),'Macao'),
('MDG',GETDATE(),'Madagaskar'),
('MWI',GETDATE(),'Malawi'),
('MYS',GETDATE(),'Malaysia'),
('MDV',GETDATE(),'Malediven'),
('MLI',GETDATE(),'Mali'),
('MLT',GETDATE(),'Malta'),
('MTQ',GETDATE(),'Martinique'),
('MRT',GETDATE(),'Mauretanien'),
('MUS',GETDATE(),'Mauritius'),
('MEX',GETDATE(),'Mexiko'),
('MCO',GETDATE(),'Monaco'),
('MNG',GETDATE(),'Mongolei'),
('MDA',GETDATE(),'Moldawien'),
('MSR',GETDATE(),'Montserrat'),
('MAR',GETDATE(),'Marokko'),
('MOZ',GETDATE(),'Mosambik'),
('OMN',GETDATE(),'Oman'),
('NAM',GETDATE(),'Namibia'),
('NRU',GETDATE(),'Nauru'),
('NPL',GETDATE(),'Nepal'),
('NLD',GETDATE(),'Niederlande'),
('ANT',GETDATE(),'Niederländische Antillen'),
('ABW',GETDATE(),'Aruba'),
('NCL',GETDATE(),'Neukaledonien'),
('VUT',GETDATE(),'Vanuatu'),
('NZL',GETDATE(),'Neuseeland'),
('NIC',GETDATE(),'Nicaragua'),
('NER',GETDATE(),'Niger'),
('NGA',GETDATE(),'Nigeria'),
('NIU',GETDATE(),'Niue'),
('NFK',GETDATE(),'Norfolkinsel'),
('NOR',GETDATE(),'Norwegen'),
('MNP',GETDATE(),'Nördliche Marianen'),
('UMI',GETDATE(),'Amerikanisch-Ozeanien'),
('FSM',GETDATE(),'Mikronesien'),
('MHL',GETDATE(),'Marshallinseln'),
('PLW',GETDATE(),'Palau'),
('PAK',GETDATE(),'Pakistan'),
('PAN',GETDATE(),'Panama'),
('PNG',GETDATE(),'Papua-Neuguinea'),
('PRY',GETDATE(),'Paraguay'),
('PER',GETDATE(),'Peru'),
('PHL',GETDATE(),'Philippinen'),
('PCN',GETDATE(),'Pitcairninseln'),
('POL',GETDATE(),'Polen'),
('PRT',GETDATE(),'Portugal'),
('GNB',GETDATE(),'Guinea-Bissau'),
('TLS',GETDATE(),'Timor-Leste'),
('PRI',GETDATE(),'Puerto Rico'),
('QAT',GETDATE(),'Katar'),
('REU',GETDATE(),'Réunion'),
('ROU',GETDATE(),'Rumänien'),
('RUS',GETDATE(),'Russische Föderation'),
('RWA',GETDATE(),'Ruanda'),
('SHN',GETDATE(),'St. Helena'),
('KNA',GETDATE(),'St. Kitts und Nevis'),
('AIA',GETDATE(),'Anguilla'),
('LCA',GETDATE(),'St. Lucia'),
('SPM',GETDATE(),'St. Pierre und Miquelon'),
('VCT',GETDATE(),'St. Vincent und die Grenadinen'),
('SMR',GETDATE(),'San Marino'),
('STP',GETDATE(),'Sao Tome and Principe'),
('SAU',GETDATE(),'Saudi-Arabien'),
('SEN',GETDATE(),'Senegal'),
('SYC',GETDATE(),'Seychellen'),
('SLE',GETDATE(),'Sierra Leone'),
('SGP',GETDATE(),'Singapur'),
('SVK',GETDATE(),'Slowakei'),
('VNM',GETDATE(),'Vietnam'),
('SVN',GETDATE(),'Slowenien'),
('SOM',GETDATE(),'Somalia'),
('ZAF',GETDATE(),'Südafrika'),
('ZWE',GETDATE(),'Simbabwe'),
('ESP',GETDATE(),'Spanien'),
('ESH',GETDATE(),'Westsahara'),
('SDN',GETDATE(),'Sudan'),
('SSD',GETDATE(),'Südsudan'),
('SUR',GETDATE(),'Suriname'),
('SJM',GETDATE(),'Svalbard and Jan Mayen'),
('SWZ',GETDATE(),'Swasiland'),
('SWE',GETDATE(),'Schweden'),
('CHE',GETDATE(),'Schweiz'),
('SYR',GETDATE(),'Arabische Republik Syrien'),
('TJK',GETDATE(),'Tadschikistan'),
('THA',GETDATE(),'Thailand'),
('TGO',GETDATE(),'Togo'),
('TKL',GETDATE(),'Tokelau'),
('TON',GETDATE(),'Tonga'),
('TTO',GETDATE(),'Trinidad und Tobago'),
('ARE',GETDATE(),'Vereinigte Arabische Emirate'),
('TUN',GETDATE(),'Tunesien'),
('TUR',GETDATE(),'Türkei'),
('TKM',GETDATE(),'Turkmenistan'),
('TCA',GETDATE(),'Turks- und Caicosinseln'),
('TUV',GETDATE(),'Tuvalu'),
('UGA',GETDATE(),'Uganda'),
('UKR',GETDATE(),'Ukraine'),
('MKD',GETDATE(),'Ehem. jugoslawische Republik Mazedonien'),
('EGY',GETDATE(),'Ägypten'),
('GBR',GETDATE(),'Vereinigtes Königreich von Großbritannien'),
('IMN',GETDATE(),'Insel Man'),
('TZA',GETDATE(),'Vereinigte Republik Tansania'),
('USA',GETDATE(),'Vereinigte Staaten von Amerika'),
('VIR',GETDATE(),'Amerikanische Jungferninseln'),
('BFA',GETDATE(),'Burkina Faso'),
('URY',GETDATE(),'Uruguay'),
('UZB',GETDATE(),'Uzbekistán'),
('VEN',GETDATE(),'Venezuela'),
('WLF',GETDATE(),'Wallis und Futuna'),
('WSM',GETDATE(),'Samoa'),
('YEM',GETDATE(),'Jemen'),
('SCG',GETDATE(),'Serbien und Montenegro'),
('ZMB',GETDATE(),'Sambia');
GO
