//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoTrader.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticker
    {
        internal object data_create;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticker()
        {
            this.TradeHistory = new HashSet<TradeHistory>();
        }
    
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public decimal rate { get; set; }
        public string currency_src { get; set; }
        public string currency_trg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeHistory> TradeHistory { get; set; }
    }
}
