//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoTrader.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int person_id { get; set; }
        public string path { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
